apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manager.yaml

configMapGenerator:
  - literals:
      - image=petri-deployer:latest
    name: deployer-image
    options:
      disableNameSuffixHash: true

generatorOptions:
  disableNameSuffixHash: true
images:
  - name: controller
    newName: controller
    newTag: latest
