apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-operator-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petri.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.operatorConfig | nindent 4 }}
