{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "petri.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: petri
{{- end }}
