# apiVersion: core.petri.run/v1alpha1
# kind: EphemeralEnvironment
# metadata:
#   labels:
#     app.kubernetes.io/name: petri
#     app.kubernetes.io/managed-by: kustomize
#   name: ephemeralenvironment-sample
# spec:
#   # TODO(user): Add fields here

apiVersion: core.petri.run/v1alpha1
kind: EphemeralEnvironment
metadata:
  name: pr-123
  namespace: default
spec:
  template: environmenttemplate-sample
  source:
    repo: https://github.com/example/app
    branch: feature-123
