# apiVersion: core.petri.run/v1alpha1
# kind: EnvironmentTemplate
# metadata:
#   labels:
#     app.kubernetes.io/name: petri
#     app.kubernetes.io/managed-by: kustomize
#   name: environmenttemplate-sample
# spec:
#   # TODO(user): Add fields here

apiVersion: core.petri.run/v1alpha1
kind: EnvironmentTemplate
metadata:
  name: environmenttemplate-sample
  namespace: default
spec:
  ingress:
    domain: example.com
  components:
    - name: nginx
      helm:
        repo: https://charts.bitnami.com/bitnami
        chart: nginx
        version: "25.0.15"
