apiVersion: core.petri.run/v1alpha1
kind: EnvironmentTemplate
metadata:
  name: environmenttemplate-sample
  namespace: default
spec:
  ttl: "24h"
  components:
    - name: nginx
      helm:
        repo: https://charts.bitnami.com/bitnami
        chart: nginx
        version: "25.0.15"
