name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  test-e2e:
    permissions:
      contents: read
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.16.4

      - name: Install Kind
        run: |
          asset="kind-linux-$(go env GOARCH)"
          url="https://github.com/kubernetes-sigs/kind/releases/download/v0.33.0"
          curl -fsSLO "$url/$asset"
          curl -fsSLO "$url/$asset.sha256sum"
          sha256sum --check "$asset.sha256sum"
          sudo install "$asset" /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Verify Helm manifests
        run: make helm-lint

      - name: Running Test e2e
        run: |
          go mod tidy
          make test-e2e
          git diff --exit-code
